### ISSUE TITLE
Implement interface deletion from CLI

### ISSUE THREAD

**Issue by coxley** [dropbox/pynsot#85] opened 2016-03-10 08:26 UTC
```bash
$ nsot interfaces            
Usage: nsot interfaces [OPTIONS] COMMAND [ARGS]...

  Interface objects.

  An Interface resource can represent a network interface attached to a
  Device. Working with interfaces is usually the device and an interface
  name.

  Interfaces can have any number of arbitrary attributes as defined below.

Options:
  -h, --help  Show this message and exit.

Commands:
  add   Add a new Interface.
  list  List existing Interfaces for a Site.


```

**Comment by jathanism** [comment] 2016-03-10 17:08
Duplicate of #68. Thanks! :)

**Closed by jathanism** 2016-03-10 17:08 UTC
Labels: duplicate
